name: Cypress Tests
on: [push]
jobs: 
  cypress-run:
    name: Cypress Automated Test Run
    runs-on: windows-latest
    steps:
    
      - name: Checkout the Main Branch
        uses: actions/checkout@v4.1.5
      - run: npm ci
        name: "Install NPM dependencies"
        
      - run: npx cypress verify
        name: "Cypress verify"
        
      - run: |
          output=$(npm run cy:ci)
          echo " Shubhammmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm $output Endddddddddddddddddddddddd"
          echo "::set-output name=cypress_output::$output"
        id: cypress
        shell: bash
        name: "Cypress Test Execution"
        
      - name: Send mail
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          # mail server settings
          server_address: smtp.gmail.com
          server_port: 465
          # Optional (recommended): mail server username:
          username: shubhammotwani2000@gmail.com
          # Optional (recommended) mail server password:
          password: wtexdyrxbzvuwgux
          # email subject
          subject: ${{ github.repository }} ${{ github.job }} is ${{ job.status }}
          # email body as text
          body: |
            ${{ github.job }} job in workflow ${{ github.workflow }} of ${{ github.repository }} is ${{ job.status }} and [here](${{ steps.cypress.outputs.cypress_output}})
          # comma-separated string, send email to
          to: shubhammotwani2000@gmail.com
          # from email name
          from: Shubham Motwani
