name: Cypress Tests
on:
  push:
jobs:
  cypress-run:
    name: Cypress Automated Test Run
    runs-on: windows-latest
    steps:
      - name: Checkout the Main Branch
        uses: actions/checkout@v4.1.5
      
      - name: Install NPM dependencies
        run: npm ci
      
      - name: Cypress verify
        run: npx cypress verify
      
      - name: Cypress Test Execution
        id: cypress
        run: |
          output=$(npm run cy:ci)
          echo "Output: $output"
          echo "cypress_output=$output" >> $GITHUB_ENV
        shell: bash
 
      - name: Send mail
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          # mail server settings
          server_address: smtp.gmail.com
          server_port: 465
          # Optional (recommended): mail server username
          username: shubhammotwani2000@gmail.com
          # Optional (recommended) mail server password
          password: wtexdyrxbzvuwgux
          # email subject
          subject: ${{ github.repository }} ${{ github.job }} is ${{ job.status }}
          # email body as text
          body: |
            ${{ github.job }} job in workflow ${{ github.workflow }} of ${{ github.repository }} is ${{ job.status }} and [here](${{ env.cypress_output }})
          # comma-separated string, send email to
          to: shubhammotwani2000@gmail.com
          # from email name
          from: Shubham Motwani
